apiVersion: apps/v1
kind: Deployment
metadata:
  name: WebapiMenuitem-deployment
  labels:
    app: WebapiMenuitem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: WebapiMenuitem
  template:
    metadata:
      labels:
        app: WebapiMenuitem
    spec:
      containers:
      - name: WebapiMenuitem
        image: acr20220620.azurecr.io/myapirepo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: myacrcredentails
---
apiVersion: v1
kind: Service
metadata:
  name: WebapiMenuitemsvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app:WebapiMenuitem
